name: 'Jar Build Steps'
description: 'Checks out code, sets up Java, and runs Gradle build'

inputs:
  module-name:
    description: 'Module name for Gradle build'
    required: true
  tag:
    description: 'Release tag for setting image version'
    required: true
  github-token:
    description: 'GitHub token for submodule checkout'
    required: true
  jvm-version:
    description: 'Java version to use'
    required: false
    default: '21'

runs:
  using: 'composite'
  steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ inputs.github-token }}

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.jvm-version }}
        distribution: 'temurin'
        cache: gradle

    - name: Set Artifact Version
      shell: bash
      run: |
        echo "Artifact version: ${{ inputs.tag }}"
        echo "version=${{ inputs.tag }}" > gradle.properties

    - name: Gradle Build
      shell: bash
      run: |
        if [ -z "${{ inputs.module-name }}" ]; then
          ./gradlew build
        else
          ./gradlew :${{ inputs.module-name }}:build
        fi
