name: CI for Composite Actions

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/ci-composite-actions.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-composite-actions:
    runs-on: ubuntu-latest
    name: Test Composite Actions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: build jar artifact
        uses: yonatankarp/github-actions/.github/actions/build-jar-artifact@main
        with:
          tag: "test-tag"

      - name: "[test] - Get Dockrfile for module - use dockerfile override"
        uses: yonatankarp/github-actions/.github/actions/get-docker-image-path@extract-dockerfile-location
        with:
          module_name: ""
          dockerfile_path: "dockerfile-location"

      - name: "[test] Get Dockrfile for module - fallback to module"
        uses: yonatankarp/github-actions/.github/actions/get-docker-image-path@extract-dockerfile-location
        with:
          module-name: "test-tag"
          dockerfile_path: ""
