name: dependabot auto merge
on:
  workflow_call:
    inputs:
      auto-update-tag:
        type: boolean
        description: Indicates weather or not to run the ./bin/replace-tag.sh to update the tag of repository after successful merge
        default: false
        required: false
      tagging-script-path:
        type: string
        description: the path to the script to execute in order to tag the repository
        required: false
        default: ./bin/replace-tag.sh
    secrets:
      GITHUB_PAT:
        required: true
        description: PAT with access of merging PRs to the repository

jobs:
  dependabot_auto_merge:
    if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: "v1"
    steps:

      # If the PR is created by Dependabot run additional steps
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a Dependabot PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        # Approving the PR and waiting for 5 sec to let GitHub UI to reflect the changes
        run: gh pr review --approve "$PR_URL" && sleep 5
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_PAT }}"

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --rebase "$PR_URL"
        id: auto-merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_PAT }}"

      - name: Move tag to current commit
        if: ${{ inputs.auto-update-tag }} == true &&
            (${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
            steps.metadata.outputs.update-type == 'version-update:semver-patch' }})
        run: sh ${{ inputs.tagging-script-path }} ${{ env.TAG_VERSION }}
