---
name: Dependabot auto-merge
on:
  workflow_call:
    secrets:
      GITHUB_PAT:
        description: "Token that can approve and merge pull requests."
        required: true

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approval for Dependabot PR
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: gh pr review --approve "$PR_URL"

      - name: Wait for Status Checks
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: gh pr checks -i 20 --watch --required "$PR_URL"

      - name: Enable auto-merge for Dependabot PRs
        id: auto-merge
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: gh pr merge --admin --rebase "$PR_URL"
