name: Continuous Integration

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  pipeline:
    name: "[ test ] pipeline"
    permissions:
      contents: read
      pull-requests: write
      checks: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: spring-skeleton
            image_name: spring-skeleton
            dockerfile_path: skeletons/spring/Dockerfile
            gradle_module: ''
          - variant: ktor-skeleton-uppercase
            image_name: KTOR-SKELETON
            dockerfile_path: skeletons/ktor/Dockerfile
            gradle_module: ''
          - variant: spring-skeleton-no-docker
            image_name: spring-skeleton
            dockerfile_path: ''
            gradle_module: ''
          - variant: spring-skeleton-submodule
            image_name: spring-skeleton
            dockerfile_path: skeletons/spring/Dockerfile
            gradle_module: ':skeletons:spring'
    uses: ./.github/workflows/ci.yml
    with:
      image-name: ${{ matrix.image_name }}
      dockerfile-path: ${{ matrix.dockerfile_path }}
      gradle-module: ${{ matrix.gradle_module }}

  dependabot_auto_merge:
    needs: pipeline
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/dependabot-auto-merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      auto-update-tag: true
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}

  linters:
    uses: ./.github/workflows/linters.yml

  update-gradle-wrapper:
    uses: ./.github/workflows/update-gradle-wrapper.yml
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}

  actions-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: devops-actions/actionlint@v0.1.12

  all-green:
    needs:
      - pipeline
      - linters
      - update-gradle-wrapper
      - actions-linter
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
