name: Continuous Integration

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  pipeline_spring:
    name: "[ test ] pipeline - spring skeleton"
    uses: ./.github/workflows/ci.yml
    with:
      app_name: spring-skeleton
      dockerfile_path: skeletons/spring/Dockerfile

  pipeline_ktor_uppercase:
    name: "[ test ] pipeline - ktor skeleton (uppercase image name sanitization)"
    uses: ./.github/workflows/ci.yml
    with:
      app_name: KTOR-SKELETON
      dockerfile_path: skeletons/ktor/Dockerfile

  pipeline_no_docker:
    name: "[ test ] pipeline - skip docker build"
    uses: ./.github/workflows/ci.yml
    with:
      app_name: spring-skeleton
      build_dockerfile: false

  dependabot_auto_merge:
    needs: pipeline_spring
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/dependabot-auto-merge.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      auto-update-tag: true
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}

  linters:
    uses: ./.github/workflows/linters.yml

  update-gradle-wrapper:
    uses: ./.github/workflows/update-gradle-wrapper.yml
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}

  actions-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: devops-actions/actionlint@v0.1.12
