name: Continuous Integration

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/ci.yml
    with:
      app_name: dummy-app

  pipeline_dockerfile_test:
    name: "[ test ] pipeline - dockerfile on project root directory:"
    uses: ./.github/workflows/ci.yml
    with:
      app_name: dummy-app
      dockerfile_path: "./Dockerfile"

  dependabot_auto_merge:
    needs: pipeline
    if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/dependabot-auto-merge.yml
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}

  linters:
    uses: ./.github/workflows/linters.yml

  update-gradle-wrapper:
    uses: ./.github/workflows/update-gradle-wrapper.yml
    secrets:
      GITHUB_PAT: ${{ secrets.CI_PAT }}
