name: Release Jar
on:
  workflow_call:
    inputs:
      module-name:
        type: string
        required: false
        description: |
          the name of the module to build and release, if none provided, the
          project would be assumed as none-modular Gradle project
        default: ""
      tag:
        type: string
        required: true
        description: the tag of this release (e.g. for SemVer `1.2.3`)
      current-branch:
        type: string
        required: false
        description: The current branch name to use for internal actions
        default: ${{ github.head_ref || github.ref_name }}
    secrets:
      GITHUB_PAT:
        required: true
        description: PAT with access to publish packages to GitHub Packages

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    steps:

      - name: Java Build Process
        uses: yonatankarp/github-actions/.github/actions/build-artifact-jar@${{ inputs.current-branch }}
        with:
          tag: ${{ inputs.tag }}
          module-name: ${{ inputs.module-name }}

      - name: Publish Artifact
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: ./gradlew publishMavenPublicationToGitHubPackagesRepository
